blueprint:
  name: Universal Hue Dimmer Control
  description: Control various functions of a Dimmer
  domain: automation
  input:
    device_id:
      name: Device ID
      description: ID of the dimmer device
      selector:
        device:
          entity:
            domain: hue
    light_entity:
      name: Light Entity
      description: Entity ID of the light to control
      selector:
        entity:
          domain: light
    counter_entity:
      name: Counter Entity
      description: Entity ID of the counter to control
      selector:
        entity:
          domain: counter
    scenes:
      name: Scenes
      description: List of scenes to activate
      selector:
        multiple: true
        action:
