blueprint:
  name: Universal Hue Dimmer Control
  description: Control various functions of a Dimmer
  domain: automation
  input:
    dimmer_device:
      name: Dimmer Remote
      description: The Dimmer Device that triggers the automation
      selector:
        device:
          multiple: false
          entity:
            - device_class: button
          filter:
            - integration: hue
    light_devices:
      name: Light
      description: The Light Devices to control
      selector:
        device:
          multiple: true
          entity:
            - domain: light
          filter:
            - integration: hue
    scene_entities:
      name: Scenes
      description: List of scenes to activate when pressing the fourth button on the dimmer remote. The scenes are selected based on the current counter value. The counter value is incremented by 1 each time the button is pressed, and loops back to start.
      selector:
        entity:
          multiple: true
          filter:
            - integration: hue
              domain: scene
    scene_counter:
      name: Scene Counter Variable
      description: Global counter variable to keep track of the scene state. This should be a Counter Helper created under "Devices and Services".
      selector:
        entity:
          multiple: false
          filter:
            - domain: counter

trigger:
  # First button, initial press
  - device_id: !input dimmer_device
    domain: hue
    platform: device
    type: initial_press
    subtype: 1
    id: Button1_InitialPress

  # Second button, initial press
  - device_id: !input dimmer_device
    domain: hue
    platform: device
    type: initial_press
    subtype: 2
    id: Button2_InitialPress

  # Second button, long press
  - device_id: !input dimmer_device
    domain: hue
    platform: device
    type: repeat
    subtype: 2
    id: Button2_LongPress

  # Third button, initial press
  - device_id: !input dimmer_device
    domain: hue
    platform: device
    type: initial_press
    subtype: 3
    id: Button3_InitialPress

  # Third button, long press
  - device_id: !input dimmer_device
    domain: hue
    platform: device
    type: repeat
    subtype: 3
    id: Button3_LongPress

  # Fourth button, initial press
  - device_id: !input dimmer_device
    domain: hue
    platform: device
    type: initial_press
    subtype: 4
    id: Button4_InitialPress

action:
  - variables:
      scene_entities: !input scene_entities
      scene_counter: !input scene_counter

  # Actions for each trigger
  - choose:
      # First button, initial press, toggle lights
      - conditions:
          - condition: trigger
            id:
              - Button1_InitialPress
        sequence:
          - repeat:
              for_each: !input light_devices
              sequence:
                - service: light.toggle
                  data: {}
                  target:
                    device_id: "{{ repeat.item }}"
          - service: counter.reset
            data: {}
            target:
              entity_id: !input scene_counter

      # Second button, initial press, increase brightness
      - conditions:
          - condition: trigger
            id:
              - Button2_InitialPress
        sequence:
          - repeat:
              for_each: !input light_devices
              sequence:
                service: light.turn_on
                data:
                  brightness_step_pct: 20
                target:
                  device_id: "{{ repeat.item }}"
          - service: counter.reset
            data: {}
            target:
              entity_id: !input scene_counter

      # Second button, long press, increase brightness continuously
      - conditions:
          - condition: trigger
            id:
              - Button2_LongPress
        sequence:
          - repeat:
              for_each: !input light_devices
              sequence:
                service: light.turn_on
                data:
                  brightness_step_pct: 20
                target:
                  device_id: "{{ repeat.item }}"
          - service: counter.reset
            data: {}
            target:
              entity_id: !input scene_counter

      # Third button, initial press, decrease brightness
      - conditions:
          - condition: trigger
            id:
              - Button3_InitialPress
        sequence:
          - repeat:
              for_each: !input light_devices
              sequence:
                service: light.turn_on
                data:
                  brightness_step_pct: -20
                target:
                  device_id: "{{ repeat.item }}"
          - service: counter.reset
            data: {}
            target:
              entity_id: !input scene_counter

      # Third button, long press, decrease brightness continuously
      - conditions:
          - condition: trigger
            id:
              - Button3_LongPress
        sequence:
          - repeat:
              for_each: !input light_devices
              sequence:
                service: light.turn_on
                data:
                  brightness_step_pct: -20
                target:
                  device_id: "{{ repeat.item }}"
          - service: counter.reset
            data: {}
            target:
              entity_id: !input scene_counter

      # Fourth button, initial press, activate scenes
      - conditions:
          - condition: trigger
            id:
              - Button4_InitialPress
        sequence:
          # Reset counter if it is larger than the number of scenes
          - if:
              - condition: template
                value_template: "{{ (states(scene_counter) | int) >= (scene_entities | length) }}"
            then:
              - service: counter.reset
                data: {}
                target:
                  entity_id: !input scene_counter

          # Increment counter to select next scene
          - service: counter.increment
            data: {}
            target:
              entity_id: !input scene_counter

          # Activate scene based on counter value
          - repeat:
              count: "{{ scene_entities | length }}"
              sequence:
                - if:
                    - condition: template
                      value_template: "{{ (states(scene_counter) | int) == (repeat.index) }}"
                  then:
                    - service: scene.turn_on
                      target:
                        entity_id: "{{ scene_entities[repeat.index - 1] }}"
                      metadata: {}
mode: single
