blueprint:
  name: Universal Hue Dimmer Control
  description: Control various functions of a Dimmer
  domain: automation
  input:
    device_id:
      name: Device ID
      description: ID of the dimmer device
      selector:
        device:
          multiple: false
          filter:
            - integration: hue
              domain: remote
    light_entity:
      name: Lights
      description: List of lights to control
      selector:
        entity:
          multiple: true
          filter:
            - domain: light
    counter_entity:
      name: Counter Entity
      description: Entity ID of the counter that controls the scenes
      selector:
        entity:
          multiple: false
          filter:
            - domain: counter
    scenes:
      name: Scenes
      description: List of scenes to activate
      selector:
        entity:
          multiple: true
          filter:
            - integration: hue
              domain: scene
