blueprint:
  name: Universal Hue Dimmer Control
  description: Control various functions of a Dimmer
  domain: automation
  input:
    dimmer_device:
      name: Dimmer Remote
      description: The Dimmer Device that triggers the automation
      selector:
        device:
          multiple: false
          entity:
            - device_class: button
          filter:
            - integration: hue
    light_devices:
      name: Lights to control
      description: The Light Devices to control
      selector:
        device:
          multiple: true
          entity:
            - domain: light
          filter:
            - integration: hue
    scene_entities:
      name: Scenes to cycle
      description: List of scenes to activate when pressing the fourth button on the dimmer remote. The scenes are selected based on the current counter value. The counter value is incremented by 1 each time the button is pressed, and loops back to start, creating a cycling effect.
      selector:
        entity:
          multiple: true
          filter:
            - integration: hue
              domain: scene
    scene_counter:
      name: Global Scene Cycling Counter Variable
      description: Global counter variable to keep track of the scene state. This should be a Counter Helper created under "Devices and Services".
      selector:
        entity:
          multiple: false
          filter:
            - domain: counter

mode: queued
max: 10
max_exceeded: silent

trigger:
  - platform: event
    event_type: hue_event
    event_data:
      device_id: !input dimmer_device

action:
  - variables:
      scene_entities: !input scene_entities
      scene_counter: !input scene_counter
      button_index: "{{ trigger.event.data.subtype }}"
      button_action: "{{ trigger.event.data.type }}"

  - alias: "Actions for each trigger"
    choose:
      - alias: "First button, toggle lights"
        conditions:
          - condition: template
            value_template: "{{ (button_index) == 1 and button_action == 'initial_press' }}"
        sequence:
          - repeat:
              for_each: !input light_devices
              sequence:
                - alias: "Toggle light"
                  service: light.toggle
                  data: {}
                  target:
                    device_id: "{{ repeat.item }}"
          - service: counter.reset
            data: {}
            target:
              entity_id: !input scene_counter

      - alias: "Second button, increase brightness"
        conditions:
          - condition: template
            value_template: "{{ (button_index) == 2 and (button_action == 'initial_press' or button_action == 'repeat') }}"
        sequence:
          - repeat:
              for_each: !input light_devices
              sequence:
                - alias: "Increase brightness"
                  service: light.turn_on
                  data:
                    brightness_step_pct: 20
                  target:
                    device_id: "{{ repeat.item }}"
          - service: counter.reset
            data: {}
            target:
              entity_id: !input scene_counter

      - alias: "Third button, decrease brightness"
        conditions:
          - condition: template
            value_template: "{{ (button_index) == 3 and (button_action == 'initial_press' or button_action == 'repeat') }}"
        sequence:
          - repeat:
              for_each: !input light_devices
              sequence:
                - alias: "Decrease brightness"
                  service: light.turn_on
                  data:
                    brightness_step_pct: -20
                  target:
                    device_id: "{{ repeat.item }}"
          - service: counter.reset
            data: {}
            target:
              entity_id: !input scene_counter

      - alias: "Fourth button, cycle scenes"
        conditions:
          - condition: template
            value_template: "{{ (button_index) == 4 and button_action == 'initial_press' }}"
        sequence:
          - if:
              - alias: "If the scene counter is larger than the number of scenes"
                condition: template
                value_template: "{{ (states(scene_counter) | int) >= (scene_entities | length) }}"
            then:
              - alias: "Reset the counter to 0"
                service: counter.reset
                data: {}
                target:
                  entity_id: !input scene_counter

          - alias: "Increment counter to select next scene"
            service: counter.increment
            data: {}
            target:
              entity_id: !input scene_counter

          - alias: "Activate scene based on counter value"
            repeat:
              count: "{{ scene_entities | length }}"
              sequence:
                if:
                  - alias: "If current scene counter value matches the repeat index"
                    condition: template
                    value_template: "{{ (states(scene_counter) | int) == (repeat.index) }}"
                then:
                  - alias: "Activate the scene"
                    service: scene.turn_on
                    target:
                      entity_id: "{{ scene_entities[repeat.index - 1] }}"
                    metadata: {}
